name: expense_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_core: ^2.27.0
  fluttertoast: ^8.2.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  firebase_database: ^10.4.10
  delayed_display: ^2.0.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - img/
